{{- if .Values.app.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dapr-cert-manager.name" . }}-metrics
  labels:
    app: {{ include "dapr-cert-manager.name" . }}
{{ include "dapr-cert-manager.labels" . | indent 4 }}
spec:
  type: {{ .Values.app.metrics.service.type }}
  ports:
    - port: {{ .Values.app.metrics.port }}
      targetPort: {{ .Values.app.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "dapr-cert-manager.name" . }}
{{- end }}

